language: python
python:
  - "3.7"
if: type = pull_request
branches:
  only:
    - master
    - develop
cache: pip

env:
  global:
    - NATHAN_PK=5JkYKpRDWeY3DN4qjZRKpEfxCqmTX17fsBJhupE9DJVVmJoGh6C
    - INIT0_PK=5J6azg8iUcQEbxEaLAFrJbcdBjgKqewLF81A63NE4T2aeHCsKiE
    - INIT1_PK=5KaTLGtpGyCbod6hM2A9RETYcNn8CMR7e7LRKLi6DPDvnF1qxEm
    - INIT2_PK=5KJe2KY1yVnnBwXDtTDGfmnRGdUdR4HpLTUqpsG39h6VexYQwWH
    - INIT3_PK=5K3FJdakQUJvLon2dBxLNUwcHJbZxW6XBvc1AJKDCiGHPyXZadz
    - INIT4_PK=5JMgujU9Zmz85buhkPQyEMXLvK7FZ6giSLjRT25uf1tpV6uPULS
    - MIGRATION_RESULT=""
  jobs:
    - PYTESTS_FILTERS=scenarios:asset_api:network_broadcast_api:registration_api:connection_to_apis GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=operations:history_api GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=database_api_first_pipeline GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=database_api_second_pipeline GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=broadcast_thousands_transactions GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=committee_member_update_global_parameters:contract_context GENESIS_FILE=genesis_update_global_parameters.json

    - PYTESTS_FILTERS=test_rpc GENESIS_FILE=genesis.json
    - PYTESTS_FILTERS=json_rpc GENESIS_FILE=genesis.json

install:  pip3 install -r requirements.txt
services:
  - docker
before_script:
  - MIGRATION_RESULT=$(docker-compose run migrate)
  - export SIDECHAIN_ADDRESS=$(echo \"$MIGRATION_RESULT\" | perl -lne '/SideChain.*contract address:\s+(0x.{40})/ && print $1')
  - sed -i "s/0xc87395b45C1c199F25a6c2Be43515C41d53751Af/$SIDECHAIN_ADDRESS/g" ./$GENESIS_FILE
  - docker-compose up -d bitcoin
  - docker-compose up -d ganache
  - docker-compose up -d echo
  - docker-compose up -d testrpc
  - docker ps -a
script:
  - python3 test_runner.py

after_script:
  - docker-compose down -v
  - docker-compose rm -fv